[workspace]
channels = [  
    "https://prefix.dev/pixi-build-backends", 
    "https://prefix.dev/conda-forge",
]
platforms = [ "linux-64", "linux-aarch64", "osx-64", "osx-arm64", "win-64" ]
preview = ["pixi-build"]

[package]
name = "FreeCAD"
version = "1.0.0"
description = "pixi instructions for FreeCAD"
authors = ["looooo <sppedflyer@gmail.com>"]

[package.build]
backend = { name = "pixi-build-rattler-build", version = "*" } 
[package.build.configuration]
extra-args = [
    "-DCMAKE_BUILD_TYPE=Release",
    "-DCMAKE_IGNORE_PREFIX_PATH='/opt/homebrew;/usr/local/homebrew'",
    "-DFREECAD_QT_VERSION=6",
    "-DBUILD_FEM_NETGEN=ON",
    "-DBUILD_WITH_CONDA=ON",
    "-DENABLE_DEVELOPER_TESTS=ON",
    "-DFREECAD_LIBPACK_USE=OFF",
    "-DFREECAD_USE_EXTERNAL_FMT=ON",
    "-DFREECAD_USE_EXTERNAL_SMESH=ON",
    "-DFREECAD_USE_PCH=OFF",
    "-DFREECAD_USE_PCL=ON",
    "-DFREECAD_USE_PYBIND11=ON",
    "-DOCC_INCLUDE_DIR=$PREFIX/include/opencascade",
    "-DQT_HOST_PATH=$PREFIX",
    "-DOCCT_CMAKE_FALLBACK=ON",
    "-DBUILD_REVERSEENGINEERING=OFF",
] 

[dependencies]
blas = "*"
calculix = "*"
ccache = "*"
cmake = "*"
coin3d = "*"
compilers = "*"
debugpy = "*"
docutils = "*"
doxygen = "*"
eigen = "*"
fmt = "*"
freetype = "*"
git = "*"
gmsh = "*"
graphviz = "*"
hdf5 = "*"
ifcopenshell = "*"
jinja2 = "*"
libboost-devel = "*"
lxml = "*"
matplotlib = "*"
nine = "*"
ninja = "*"
noqt5 = "*"
numpy = "*"
occt = "*"
olefile = "*"
opencamlib = "*"
opencv = "*"
openssl = "*"
pandas = "*"
pcl = "*"
pip = "*"
pivy = "*"
pixi-pack = "*"
ply = "*"
pre-commit = "*"
pybind11 = "*"
pycollada = "*" 
pyside6 = "*"
python = "*"
pythonocc-core = "*"
pyyaml = "*"
qt6-main = "*"
rattler-build = "*"
requests = "*"
scipy = "*"
six = "*"
smesh = "*"
swig = "*"
vtk = "*"
xerces-c = "*"
xlutils = "*"
yaml-cpp = "*"
zlib = "*"

## Linux Dependencies (x86-64)
[target.linux-64.dependencies]
kernel-headers_linux-64 = "*"
libdrm-cos7-x86_64 = "*"
libselinux-cos7-x86_64 = "*"
libsepol-cos7-x86_64 = "*"
libspnav = "*"
libx11-common-cos7-x86_64 = "*"
libx11-cos7-x86_64 = "*"
libxau-cos7-x86_64 = "*"
libxcb-cos7-x86_64 = "*"
libxdamage-cos7-x86_64 = "*"
libxext-cos7-x86_64 = "*"
libxfixes-cos7-x86_64 = "*"
libxi-cos7-x86_64 = "*"
libxi-devel-cos7-x86_64 = "*"
libxxf86vm-cos7-x86_64 = "*"
mesa-dri-drivers-cos7-x86_64 = "*"
mesa-libegl-cos7-x86_64 = "*"
mesa-libegl-devel-cos7-x86_64 = "*"
mesa-libgl-cos7-x86_64 = "*"
mesa-libgl-devel-cos7-x86_64 = "*"
pixman-cos7-x86_64 = "*"
sed = "*"
sysroot_linux-64 = "*"
xorg-x11-server-common-cos7-x86_64 = "*"
xorg-x11-server-xvfb-cos7-x86_64 = "*"
xorg-xproto = "*"

## Linux Dependencies (aarch64)
[target.linux-aarch64.dependencies]
kernel-headers_linux-aarch64 = "*"
libdrm-cos7-aarch64 = "*"
libglvnd-cos7-aarch64 = "*"
libglvnd-glx-cos7-aarch64 = "*"
libselinux-cos7-aarch64 = "*"
libsepol-cos7-aarch64 = "*"
libspnav = "*"
libx11-common-cos7-aarch64 = "*"
libx11-cos7-aarch64 = "*"
libxau-cos7-aarch64 = "*"
libxcb-cos7-aarch64 = "*"
libxdamage-cos7-aarch64 = "*"
libxext-cos7-aarch64 = "*"
libxfixes-cos7-aarch64 = "*"
libxi-cos7-aarch64 = "*"
libxi-devel-cos7-aarch64 = "*"
libxxf86vm-cos7-aarch64 = "*"
mesa-dri-drivers-cos7-aarch64 = "*"
mesa-khr-devel-cos7-aarch64 = "*"
mesa-libegl-cos7-aarch64 = "*"
mesa-libegl-devel-cos7-aarch64 = "*"
mesa-libgbm-cos7-aarch64 = "*"
mesa-libgl-cos7-aarch64 = "*"
mesa-libgl-devel-cos7-aarch64 = "*"
mesa-libglapi-cos7-aarch64 = "*"
pixman-cos7-aarch64 = "*"
sed = "*"
sysroot_linux-aarch64 = "*"
xorg-x11-server-common-cos7-aarch64 = "*"
xorg-x11-server-xvfb-cos7-aarch64 = "*"
xorg-xproto = "*"

## macOS Dependencies (Intel)
[target.osx-64.dependencies]
blas = { version = "*", build = "blis" }
dmgbuild = "*"
sed = "*"

## macOS Dependencies (Apple Silicon)
[target.osx-arm64.dependencies]
blas = { version = "*", build = "accelerate" }
dmgbuild = "*"
sed = "*"

## Qt 6 Configuration Presets
[target.linux-64.tasks]
configure = { cmd = [ "cmake", "-B", "build", "--preset", "conda-linux-debug", "-DFREECAD_QT_VERSION=6", "-DBUILD_REVERSEENGINEERING=OFF" ], depends-on = ["initialize"]}
configure-debug = { cmd = [ "cmake", "-B", "build", "--preset", "conda-linux-debug", "-DFREECAD_QT_VERSION=6", "-DBUILD_REVERSEENGINEERING=OFF" ], depends-on = ["initialize"]}
configure-release = { cmd = [ "cmake", "-B", "build", "--preset", "conda-linux-release", "-DFREECAD_QT_VERSION=6", "-DBUILD_REVERSEENGINEERING=OFF" ], depends-on = ["initialize"]}

[target.linux-aarch64.tasks]
configure = { cmd = [ "cmake", "-B", "build", "--preset", "conda-linux-debug", "-DFREECAD_QT_VERSION=6", "-DBUILD_REVERSEENGINEERING=OFF" ], depends-on= ["initialize"]}
configure-debug = { cmd = [ "cmake", "-B", "build", "--preset", "conda-linux-debug", "-DFREECAD_QT_VERSION=6", "-DBUILD_REVERSEENGINEERING=OFF" ], depends-on= ["initialize"]}
configure-release = { cmd = [ "cmake", "-B", "build", "--preset", "conda-linux-release", "-DFREECAD_QT_VERSION=6", "-DBUILD_REVERSEENGINEERING=OFF" ], depends-on= ["initialize"]}

[target.osx-64.tasks]
configure = { cmd = [ "cmake", "-B", "build", "--preset", "conda-macos-debug", "-DFREECAD_QT_VERSION=6", "-DBUILD_REVERSEENGINEERING=OFF" ], depends-on = ["initialize"]}
configure-debug = { cmd = [ "cmake", "-B", "build", "--preset", "conda-macos-debug", "-DFREECAD_QT_VERSION=6", "-DBUILD_REVERSEENGINEERING=OFF" ], depends-on = ["initialize"]}
configure-release = { cmd = [ "cmake", "-B", "build", "--preset", "conda-macos-release", "-DFREECAD_QT_VERSION=6", "-DBUILD_REVERSEENGINEERING=OFF" ], depends-on = ["initialize"]}

[target.osx-arm64.tasks]
configure = { cmd = [ "cmake", "-B", "build", "--preset", "conda-macos-debug", "-DFREECAD_QT_VERSION=6", "-DBUILD_REVERSEENGINEERING=OFF" ], depends-on = ["initialize"]}
configure-debug = { cmd = [ "cmake", "-B", "build", "--preset", "conda-macos-debug", "-DFREECAD_QT_VERSION=6", "-DBUILD_REVERSEENGINEERING=OFF" ], depends-on = ["initialize"]}
configure-release = { cmd = [ "cmake", "-B", "build", "--preset", "conda-macos-release", "-DFREECAD_QT_VERSION=6", "-DBUILD_REVERSEENGINEERING=OFF" ], depends-on = ["initialize"]}
package = { cmd = "package/pixi/macos/create_bundle.sh", depends-on = ["build"]}

[target.win-64.tasks]
configure = { cmd = [ "cmake", "-B", "build", "--preset", "conda-windows-debug", "-DFREECAD_QT_VERSION=6", "-DBUILD_REVERSEENGINEERING=OFF" ], depends-on = ["initialize"]}
configure-debug = { cmd = [ "cmake", "-B", "build", "--preset", "conda-windows-debug", "-DFREECAD_QT_VERSION=6", "-DBUILD_REVERSEENGINEERING=OFF" ], depends-on = ["initialize"]}
configure-release = { cmd = [ "cmake", "-B", "build", "--preset", "conda-windows-release", "-DFREECAD_QT_VERSION=6", "-DBUILD_REVERSEENGINEERING=OFF" ], depends-on = ["initialize"]}
freecad = { cmd = [ ".pixi/envs/default/Library/bin/FreeCAD.exe" ], depends-on = ["install"]}

## Tasks
[tasks]
initialize = { cmd = ["git", "submodule", "update", "--init", "--recursive"]}
build = { cmd = [ "cmake", "--build", "build" ] }
install = { cmd = [ "cmake", "--install", "build" ] }
test = { cmd = [ "ctest", "--test-dir", "build" ] }
freecad = "build/bin/FreeCAD"
