[workspace]
channels = [
    "https://prefix.dev/pixi-build-backends",
    "https://prefix.dev/conda-forge",
]
platforms = ["linux-64", "linux-aarch64", "osx-64", "osx-arm64", "win-64"]
preview = ["pixi-build"]

[package]
name = "freecad"
homepage = "https://freecad.org"
repository = "https://github.com/FreeCAD/FreeCAD"
version = "1.1.0dev"
description = "pixi instructions for FreeCAD"

[package.build]
backend = { name = "pixi-build-rattler-build", version = "*" }

[dependencies]
freecad = { path = "." }

## Linux Dependencies (x86-64)
[target.linux-64.dependencies]
sed = "*"

## Linux Dependencies (aarch64)
[target.linux-aarch64.dependencies]
sed = "*"

## macOS Dependencies (Intel)
[target.osx-64.dependencies]
dmgbuild = "*"

## macOS Dependencies (Apple Silicon)
[target.osx-arm64.dependencies]
dmgbuild = "*"
